# Generated by Django 5.1.1 on 2024-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigndoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Contact', models.BigIntegerField()),
                ('Email', models.CharField(max_length=25)),
                ('Symptoms', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='adddepartments',
            name='Department',
            field=models.CharField(max_length=50),
        ),
    ]
