# Generated by Django 5.1.1 on 2024-10-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosapp', '0002_appointmentshedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=20)),
                ('Time', models.TimeField(max_length=20)),
                ('bill', models.IntegerField()),
            ],
        ),
    ]
