# Generated by Django 5.1.1 on 2024-10-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosapp', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=20)),
                ('Medicines', models.CharField(max_length=50)),
                ('Test', models.CharField(max_length=20)),
            ],
        ),
    ]
