# Generated by Django 5.1.1 on 2024-10-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosapp', '0004_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
