# Generated by Django 5.1.1 on 2024-10-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosapp', '0006_alter_schedule_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Contact',
        ),
    ]
