# Generated by Django 5.1.1 on 2024-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosapp', '0007_remove_schedule_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
