# Generated by Django 5.1.1 on 2024-09-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='Age',
            field=models.DateField(),
        ),
    ]
