# Generated by Django 5.1.1 on 2024-09-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0002_register_status_alter_register_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='P_Register',
        ),
    ]
