# Generated by Django 5.1.1 on 2024-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0003_rename_register_p_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Symptoms', models.CharField(max_length=250)),
                ('Contact', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Age', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=15)),
                ('Status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='P_Register',
        ),
    ]
