# Generated by Django 5.1.1 on 2024-10-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0004_appointment_register_delete_p_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
