# Generated by Django 5.1.1 on 2024-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0005_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Symptoms',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
