# Generated by Django 5.1.1 on 2024-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0006_alter_appointment_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=25)),
                ('Branch', models.CharField(max_length=25)),
                ('cardno', models.CharField(max_length=25)),
                ('cardholder', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
