# Generated by Django 5.1.1 on 2024-10-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsapp', '0007_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='cardno',
            new_name='IFSC',
        ),
    ]
